### ISSUE TITLE
Package could not be referenced

### ISSUE THREAD

**Issue by bathclin** [MicrosoftDocs/visualstudio-docs.ja-jp#83]
I ran it according to the procedure, but the next package was not installed and I installed it manually.

pandas, sklearn

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 44d264fa-6d4e-0128-b0a0-f997d01c19a9
* Version Independent ID: 7d2e1867-4890-20fc-f60c-45f0242b4f7f
* Content: [クイック スタート - Cookiecutter を使用して Python プロジェクトを作成する - Visual Studio](https://docs.microsoft.com/ja-jp/visualstudio/python/quickstart-04-python-in-visual-studio-project-from-cookiecutter?view=vs-2017)
* Content Source: [docs/python/quickstart-04-python-in-visual-studio-project-from-cookiecutter.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/python/quickstart-04-python-in-visual-studio-project-from-cookiecutter.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by LisandroSu** [comment]
Hello, @bathclin 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #1805](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1805) via [**ZenHub**](https://www.zenhub.com/)
